version: "3"

services:
  web:
    build: .
    image: graph_maker
    command: ./start.sh
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/graph_maker
  db:
    image: postgres:latest
